name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - run: go version
      - name: Build services
        run: |
          cd gateway && go build ./...
          cd ../services/user && go build ./...
          cd ../services/video && go build ./...
          cd ../services/social && go build ./...
          cd ../services/recommend && go build ./...
      - name: Build web
        uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: |
          cd webapp && npm ci && npm run build
